export const VALIDATION = {
  EMAIL_REGEX: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_RESET_TOKEN_EXPIRY_HOURS: 1,
  EMAIL_VERIFICATION_TOKEN_EXPIRY_HOURS: 24,
  PHONE_REGEX: /^\+[1-9]\d{1,14}$/,
  PHONE_VERIFICATION_CODE_LENGTH: 6,
  PHONE_VERIFICATION_CODE_EXPIRY_MINUTES: 10,
} as const;
